name: Build Packages

on:
  push:
    branches:
      - main

jobs:
  build-packages:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [base-files, base-passwd, bash, bsdutils, coreutils, dash, debconf, debianutils, diffutils, dpkg, e2fsprogs, findutils, gcc-14-base, grep, gzip, hostname, init-system-helpers, libacl1, libattr1, libaudit-common, libaudit1, libblkid1, libbz2-1.0, libc-bin, libc6, libcap-ng0, libcap2, libcom-err2, libcrypt1, libdebconfclient0, libext2fs2t64, libgcc-s1, libgcrypt20, libgmp10, libgpg-error0, liblz4-1, liblzma5, libmd0, libmount1, libncursesw6, libpam-modules, libpam-modules-bin, libpam-runtime, libpam0g, libpcre2-8-0, libproc2-0, libselinux1, libsemanage-common, libsemanage2, libsepol2, libsmartcols1, libss2, libssl3t64, libsystemd0, libtinfo6, libudev1, libuuid1, libzstd1, login, logsave, mawk, mount, ncurses-base, ncurses-bin, passwd, perl-base, procps, sed, sensible-utils, sysvinit-utils, tar, util-linux, zlib1g, adduser, apt, apt-utils, ca-certificates, console-setup, console-setup-linux, cron, cron-daemon-common, dbus, dbus-bin, dbus-daemon, dbus-session-bus-common, dbus-system-bus-common, dbus-user-session, debconf-i18n, dhcpcd-base, distro-info, distro-info-data, dmsetup, eject, gir1.2-girepository-2.0, gir1.2-glib-2.0, gpgv, init, iproute2, iputils-ping, iso-codes, kbd, keyboard-configuration, kmod, krb5-locales, less, libapparmor1, libapt-pkg6.0t64, libargon2-1, libassuan0, libatm1t64, libbpf1, libbsd0, libcap2-bin, libcryptsetup12, libdb5.3t64, libdbus-1-3, libdevmapper1.02.1, libelf1t64, libestr0, libexpat1, libfastjson4, libfdisk1, libffi8, libfribidi0, libgirepository-1.0-1, libglib2.0-0t64, libglib2.0-data, libgnutls30t64, libgssapi-krb5-2, libhogweed6t64, libicu74, libidn2-0, libjson-c5, libk5crypto3, libkeyutils1, libkmod2, libkrb5-3, libkrb5support0, liblocale-gettext-perl, libmnl0, libnetplan1, libnettle8t64, libnewt0.52, libnpth0t64, libnss-systemd, libp11-kit0, libpam-cap, libpam-systemd, libpopt0, libpython3-stdlib, libpython3.12-minimal, libpython3.12-stdlib, libreadline8t64, libseccomp2, libslang2, libsqlite3-0, libstdc++6, libsystemd-shared, libtasn1-6, libtext-charwidth-perl, libtext-iconv-perl, libtext-wrapi18n-perl, libtirpc-common, libtirpc3t64, libunistring5, libxml2, libxtables12, libxxhash0, libyaml-0-2, locales, logrotate, lsb-release, media-types, netbase, netcat-openbsd, netplan-generator, netplan.io, networkd-dispatcher, openssl, python-apt-common, python3, python3-apt, python3-cffi-backend, python3-dbus, python3-gi, python3-markdown-it, python3-mdurl, python3-minimal, python3-netifaces, python3-netplan, python3-pkg-resources, python3-pygments, python3-rich, python3-typing-extensions, python3-yaml, python3.12, python3.12-minimal, readline-common, rsyslog, shared-mime-info, sudo, systemd, systemd-dev, systemd-hwe-hwdb, systemd-resolved, systemd-sysv, systemd-timesyncd, tzdata, ubuntu-keyring, ubuntu-minimal, ubuntu-pro-client, ubuntu-pro-client-l10n, ucf, udev, usrmerge, vim-common, vim-tiny, whiptail, xdg-user-dirs, xkb-data, xxd]
    steps:
      - name: Update ubuntu.sources
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
      - name: Set the environment variables
        run: echo "PACKAGE=${{ matrix.package }}" >> $GITHUB_ENV
      - name: Get the source
        run: |
          sudo apt update
          apt source $PACKAGE
      - name: Get the dependencies
        run: |
          sudo apt build-dep $PACKAGE
      - name: Build the package
        run: |
          cd "$(ls -d */)"
          dpkg-buildpackage -us -uc
          sudo mkdir /artifacts
          sudo mv ../*.deb /artifacts/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ matrix.package }}
          path: "/artifacts/*"
