# This is a basic workflow to help you get started with Actions

name: "Build Dependencies"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update ubuntu.sources to enable deb-src
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
      - name: Set the enviorment variables
        run: "echo 'PACKAGE=base-files' >> $GITHUB_ENV"
      - name: Get the source
        run: |
          sudo apt update
          apt source $PACKAGE
      - name: Get the dependencies
        run: |
          cd "$(ls -d */)"
          sudo apt build-dep $PACKAGE
