# This is a basic workflow to help you get started with Actions

name: "Build Dependencies"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  base-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Update ubuntu.sources
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
      - name: Set the enviorment variables
        run: "echo 'PACKAGE=base-files' >> $GITHUB_ENV"
      - name: Get the source
        run: |
          sudo apt update
          apt source $PACKAGE
      - name: Get the dependencies
        run: |
          sudo apt build-dep $PACKAGE
      - name: Build the package
        run: |
          cd "$(ls -d */)"
          dpkg-buildpackage -us -uc
          sudo mkdir /artifacts
          sudo mv ../*.deb /artifacts/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: base-files
          path: "/artifacts/*"
  base-passwd:
    runs-on: ubuntu-24.04
    steps:
      - name: Update ubuntu.sources
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
      - name: Set the enviorment variables
        run: "echo 'PACKAGE=base-passwd' >> $GITHUB_ENV"
      - name: Get the source
        run: |
          sudo apt update
          apt source $PACKAGE
      - name: Get the dependencies
        run: |
          sudo apt build-dep $PACKAGE
      - name: Build the package
        run: |
          cd "$(ls -d */)"
          dpkg-buildpackage -us -uc
          sudo mkdir /artifacts
          sudo mv ../*.deb /artifacts/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: base-passwd
          path: "/artifacts/*"
