name: Build Packages

on:
  push:
    branches:
      - main

jobs:
  build-packages:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [base-files, base-passwd, bash, bsdutils, coreutils, dash, debconf, debianutils, diffutils, dpkg, e2fsprogs, findutils, gcc-14-base, grep, gzip, hostname, init-system-helpers, libacl1, libkeyutils1, ...]
    steps:
      - name: Update ubuntu.sources
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
      - name: Set the environment variables
        run: echo "PACKAGE=${{ matrix.package }}" >> $GITHUB_ENV
      - name: Get the source
        run: |
          sudo apt update
          apt source $PACKAGE
      - name: Get the dependencies
        run: |
          sudo apt build-dep $PACKAGE
      - name: Build the package
        run: |
          cd "$(ls -d */)"
          if [ "$PACKAGE" = "libkeyutils1" ]; then
            sudo dpkg-buildpackage -us -uc
          else
            dpkg-buildpackage -us -uc
          fi
          sudo mkdir /artifacts
          sudo mv ../*.deb /artifacts/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ matrix.package }}
          path: "/artifacts/*"
